import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8');
const users = read('src/actions/users.ts');
const teams = read('src/actions/teams.ts');
const writer = read('src/lib/db/evaluations-write.ts');
const migration = read('supabase/migrations/20260911000400_personnel_actor_guard.sql');
const rollback = read('db/rollback-personnel-actor-guard.sql');

assert.match(users, /data: existingUser, error: existingUserError/);
assert.match(users, /if \(existingUserError\)/);
assert.match(users, /applyPersonnelTransaction\(\[payload\], null, auth\.user\.id\)/);
assert.match(users, /applyPersonnelTransaction\(prepared\.map\(\(item\) => item\.payload\), null, auth\.user\.id\)/);
assert.match(users, /applyPersonnelTransaction\(\[\{ id, is_active: false \}\], null, auth\.user\.id\)/);
assert.doesNotMatch(users, /\.from\('users'\)\s*\n\s*\.update\(\{ is_active: false \}\)/);
assert.match(teams, /applyPersonnelTransaction\(\[\], dbTeam, auth\.user\.id\)/);
assert.match(teams, /applyPersonnelTransaction\(\[\], \{ id, is_active: false \}, auth\.user\.id\)/);
assert.match(writer, /actorId: string/);
assert.match(writer, /p_actor_id: actorId/);
assert.match(migration, /p_actor_id uuid/);
assert.match(migration, /LOCK TABLE public\.teams, public\.users, public\.evaluation_rounds IN SHARE ROW EXCLUSIVE MODE/);
assert.match(migration, /v_actor\.role NOT IN \('Manager', 'Leader'\)/);
assert.match(migration, /v_target_team_id IS DISTINCT FROM v_actor\.team_id/);
assert.match(migration, /P102M3T05_DELETE_REFERENCED_(LEADER|SUBLEADER|EVALUATOR)/);
assert.match(migration, /SECURITY DEFINER/);
assert.match(migration, /REVOKE ALL ON FUNCTION public\.apply_personnel_transaction\(jsonb,jsonb,uuid\)/);
assert.match(rollback, /P102M3T05_ROLLBACK_PREFLIGHT_(OWNER|SECURITY|PROVENANCE|BODY)/);
assert.match(rollback, /DROP FUNCTION public\.apply_personnel_transaction\(jsonb,jsonb,uuid\)/);
console.log('PERSONNEL_ACTION_BOUNDARY PASS cases=19');
